version: '3'

services:
  flight-tracker:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
